### PR TITLE
Show and search full command names

### LINKED ISSUE #36: Add autocomplete for command labels

### PR DESCRIPTION
**Pull request by mnquintana**
Resolves #36 
### Before

screenshot 2015-04-14 10 23 46
### After

screenshot 2015-04-14 00 09 14

/cc @atom/non-github-maintainers Anyone wanna take a look?
/cc @l4u

### CODE REVIEW

**Comment by mnquintana** [comment]
For maximum benefit, I think we'd need to implement atom/atom#6374 too.

**Comment by thedaniel** [comment]
Strong -1 unless command names and human-readable command names can be significantly different, which they can't currently.

**Comment by mnquintana** [comment]
@thedaniel Right, that would take atom/atom#6373. Although what I'd actually like to do in the meantime is keep the display the same, but still allow searching for the full command names. That seems like a reasonable compromise.

**Comment by damieng** [comment]
As this hasn't been worked on in over a year and was a work in progress can we close it?

**Comment by mnquintana** [comment]
Might return to this at some point, but definitely not in its current state

**Pull request closed without merging**
